In [9]:
import numpy



a = numpy.array([1, 2, 3, 4, 5])


print(a)

[1 2 3 4 5]


In [10]:
import numpy



a = numpy.array([1, 2, 3, 4, 5])


print(a * a)

[ 1  4  9 16 25]


In [11]:
import numpy



a = numpy.array([1, 2, 3, 4, 5])


print(a**a)

[   1    4   27  256 3125]


In [12]:
import numpy as np



a = np.array([1, 2, 3, 4, 5])


print(a)

[1 2 3 4 5]


In [13]:
import numpy



print(numpy.__version__)

2.3.1


In [14]:
import numpy as np

a = np.array(1)
print(a)

b = np.array([1, 2, 3])
print(b)

c = np.array([[1, 2, 3], [4, 5, 6]])
print(c)

d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(d)

e = np.array([1, 2, 3, 4], ndmin=5)
print(e)

1
[1 2 3]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[[[1 2 3 4]]]]]


In [15]:
import numpy as np

a = np.array(1)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
e = np.array([1, 2, 3, 4], ndmin=5)

print("Dimensions of a:", a.ndim)
print("Dimensions of b:", b.ndim)
print("Dimensions of c:", c.ndim)
print("Dimensions of d:", d.ndim)
print("Dimensions of e:", e.ndim)

Dimensions of a: 0
Dimensions of b: 1
Dimensions of c: 2
Dimensions of d: 2
Dimensions of e: 5


In [16]:
import numpy as np

array2D = np.array([[1, 2, 3], [4, 5, 6]])

print("Array elements array2D(0, 1): ", array2D[0, 1])
print("Array elements array2D(1, 2): ", array2D[1, 2])

array3D = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("Array elements array3D(0, 1, 2): ", array3D[0, 1, 2])

Array elements array2D(0, 1):  2
Array elements array2D(1, 2):  6
Array elements array3D(0, 1, 2):  6


In [17]:
import numpy as np

array2D = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("Elements of second row:", array2D[1])
print("Elements of second row:", array2D[1, :])
print("Elements of fourth column:", array2D[:, 3])

Elements of second row: [ 6  7  8  9 10]
Elements of second row: [ 6  7  8  9 10]
Elements of fourth column: [4 9]
